package com.aotubuy.Model;

import java.io.Serializable;
import java.math.BigDecimal;

public class DollUsers implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_users.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_users.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_users.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_users.sex
     *
     * @mbggenerated
     */
    private Boolean sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_users.birthday
     *
     * @mbggenerated
     */
    private Integer birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_users.user_money
     *
     * @mbggenerated
     */
    private BigDecimal userMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_users.frozen_money
     *
     * @mbggenerated
     */
    private BigDecimal frozenMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_users.distribut_money
     *
     * @mbggenerated
     */
    private BigDecimal distributMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_users.pay_points
     *
     * @mbggenerated
     */
    private Integer payPoints;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_users.address_id
     *
     * @mbggenerated
     */
    private Integer addressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_users.reg_time
     *
     * @mbggenerated
     */
    private Integer regTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_users.last_login
     *
     * @mbggenerated
     */
    private Integer lastLogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_users.last_ip
     *
     * @mbggenerated
     */
    private String lastIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_users.qq
     *
     * @mbggenerated
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_users.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_users.mobile_validated
     *
     * @mbggenerated
     */
    private Byte mobileValidated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_users.oauth
     *
     * @mbggenerated
     */
    private String oauth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_users.openid
     *
     * @mbggenerated
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_users.head_pic
     *
     * @mbggenerated
     */
    private String headPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_users.province
     *
     * @mbggenerated
     */
    private Integer province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_users.city
     *
     * @mbggenerated
     */
    private Integer city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_users.district
     *
     * @mbggenerated
     */
    private Integer district;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_users.email_validated
     *
     * @mbggenerated
     */
    private Boolean emailValidated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_users.nickname
     *
     * @mbggenerated
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_users.level
     *
     * @mbggenerated
     */
    private Boolean level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_users.discount
     *
     * @mbggenerated
     */
    private BigDecimal discount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_users.total_amount
     *
     * @mbggenerated
     */
    private BigDecimal totalAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_users.is_lock
     *
     * @mbggenerated
     */
    private Boolean isLock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_users.is_distribut
     *
     * @mbggenerated
     */
    private Boolean isDistribut;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_users.first_leader
     *
     * @mbggenerated
     */
    private Integer firstLeader;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_users.second_leader
     *
     * @mbggenerated
     */
    private Integer secondLeader;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_users.third_leader
     *
     * @mbggenerated
     */
    private Integer thirdLeader;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_users.token
     *
     * @mbggenerated
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table doll_users
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_users.user_id
     *
     * @return the value of doll_users.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_users.user_id
     *
     * @param userId the value for doll_users.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_users.email
     *
     * @return the value of doll_users.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_users.email
     *
     * @param email the value for doll_users.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_users.password
     *
     * @return the value of doll_users.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_users.password
     *
     * @param password the value for doll_users.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_users.sex
     *
     * @return the value of doll_users.sex
     *
     * @mbggenerated
     */
    public Boolean getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_users.sex
     *
     * @param sex the value for doll_users.sex
     *
     * @mbggenerated
     */
    public void setSex(Boolean sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_users.birthday
     *
     * @return the value of doll_users.birthday
     *
     * @mbggenerated
     */
    public Integer getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_users.birthday
     *
     * @param birthday the value for doll_users.birthday
     *
     * @mbggenerated
     */
    public void setBirthday(Integer birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_users.user_money
     *
     * @return the value of doll_users.user_money
     *
     * @mbggenerated
     */
    public BigDecimal getUserMoney() {
        return userMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_users.user_money
     *
     * @param userMoney the value for doll_users.user_money
     *
     * @mbggenerated
     */
    public void setUserMoney(BigDecimal userMoney) {
        this.userMoney = userMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_users.frozen_money
     *
     * @return the value of doll_users.frozen_money
     *
     * @mbggenerated
     */
    public BigDecimal getFrozenMoney() {
        return frozenMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_users.frozen_money
     *
     * @param frozenMoney the value for doll_users.frozen_money
     *
     * @mbggenerated
     */
    public void setFrozenMoney(BigDecimal frozenMoney) {
        this.frozenMoney = frozenMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_users.distribut_money
     *
     * @return the value of doll_users.distribut_money
     *
     * @mbggenerated
     */
    public BigDecimal getDistributMoney() {
        return distributMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_users.distribut_money
     *
     * @param distributMoney the value for doll_users.distribut_money
     *
     * @mbggenerated
     */
    public void setDistributMoney(BigDecimal distributMoney) {
        this.distributMoney = distributMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_users.pay_points
     *
     * @return the value of doll_users.pay_points
     *
     * @mbggenerated
     */
    public Integer getPayPoints() {
        return payPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_users.pay_points
     *
     * @param payPoints the value for doll_users.pay_points
     *
     * @mbggenerated
     */
    public void setPayPoints(Integer payPoints) {
        this.payPoints = payPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_users.address_id
     *
     * @return the value of doll_users.address_id
     *
     * @mbggenerated
     */
    public Integer getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_users.address_id
     *
     * @param addressId the value for doll_users.address_id
     *
     * @mbggenerated
     */
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_users.reg_time
     *
     * @return the value of doll_users.reg_time
     *
     * @mbggenerated
     */
    public Integer getRegTime() {
        return regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_users.reg_time
     *
     * @param regTime the value for doll_users.reg_time
     *
     * @mbggenerated
     */
    public void setRegTime(Integer regTime) {
        this.regTime = regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_users.last_login
     *
     * @return the value of doll_users.last_login
     *
     * @mbggenerated
     */
    public Integer getLastLogin() {
        return lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_users.last_login
     *
     * @param lastLogin the value for doll_users.last_login
     *
     * @mbggenerated
     */
    public void setLastLogin(Integer lastLogin) {
        this.lastLogin = lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_users.last_ip
     *
     * @return the value of doll_users.last_ip
     *
     * @mbggenerated
     */
    public String getLastIp() {
        return lastIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_users.last_ip
     *
     * @param lastIp the value for doll_users.last_ip
     *
     * @mbggenerated
     */
    public void setLastIp(String lastIp) {
        this.lastIp = lastIp == null ? null : lastIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_users.qq
     *
     * @return the value of doll_users.qq
     *
     * @mbggenerated
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_users.qq
     *
     * @param qq the value for doll_users.qq
     *
     * @mbggenerated
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_users.mobile
     *
     * @return the value of doll_users.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_users.mobile
     *
     * @param mobile the value for doll_users.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_users.mobile_validated
     *
     * @return the value of doll_users.mobile_validated
     *
     * @mbggenerated
     */
    public Byte getMobileValidated() {
        return mobileValidated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_users.mobile_validated
     *
     * @param mobileValidated the value for doll_users.mobile_validated
     *
     * @mbggenerated
     */
    public void setMobileValidated(Byte mobileValidated) {
        this.mobileValidated = mobileValidated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_users.oauth
     *
     * @return the value of doll_users.oauth
     *
     * @mbggenerated
     */
    public String getOauth() {
        return oauth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_users.oauth
     *
     * @param oauth the value for doll_users.oauth
     *
     * @mbggenerated
     */
    public void setOauth(String oauth) {
        this.oauth = oauth == null ? null : oauth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_users.openid
     *
     * @return the value of doll_users.openid
     *
     * @mbggenerated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_users.openid
     *
     * @param openid the value for doll_users.openid
     *
     * @mbggenerated
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_users.head_pic
     *
     * @return the value of doll_users.head_pic
     *
     * @mbggenerated
     */
    public String getHeadPic() {
        return headPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_users.head_pic
     *
     * @param headPic the value for doll_users.head_pic
     *
     * @mbggenerated
     */
    public void setHeadPic(String headPic) {
        this.headPic = headPic == null ? null : headPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_users.province
     *
     * @return the value of doll_users.province
     *
     * @mbggenerated
     */
    public Integer getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_users.province
     *
     * @param province the value for doll_users.province
     *
     * @mbggenerated
     */
    public void setProvince(Integer province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_users.city
     *
     * @return the value of doll_users.city
     *
     * @mbggenerated
     */
    public Integer getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_users.city
     *
     * @param city the value for doll_users.city
     *
     * @mbggenerated
     */
    public void setCity(Integer city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_users.district
     *
     * @return the value of doll_users.district
     *
     * @mbggenerated
     */
    public Integer getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_users.district
     *
     * @param district the value for doll_users.district
     *
     * @mbggenerated
     */
    public void setDistrict(Integer district) {
        this.district = district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_users.email_validated
     *
     * @return the value of doll_users.email_validated
     *
     * @mbggenerated
     */
    public Boolean getEmailValidated() {
        return emailValidated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_users.email_validated
     *
     * @param emailValidated the value for doll_users.email_validated
     *
     * @mbggenerated
     */
    public void setEmailValidated(Boolean emailValidated) {
        this.emailValidated = emailValidated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_users.nickname
     *
     * @return the value of doll_users.nickname
     *
     * @mbggenerated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_users.nickname
     *
     * @param nickname the value for doll_users.nickname
     *
     * @mbggenerated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_users.level
     *
     * @return the value of doll_users.level
     *
     * @mbggenerated
     */
    public Boolean getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_users.level
     *
     * @param level the value for doll_users.level
     *
     * @mbggenerated
     */
    public void setLevel(Boolean level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_users.discount
     *
     * @return the value of doll_users.discount
     *
     * @mbggenerated
     */
    public BigDecimal getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_users.discount
     *
     * @param discount the value for doll_users.discount
     *
     * @mbggenerated
     */
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_users.total_amount
     *
     * @return the value of doll_users.total_amount
     *
     * @mbggenerated
     */
    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_users.total_amount
     *
     * @param totalAmount the value for doll_users.total_amount
     *
     * @mbggenerated
     */
    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_users.is_lock
     *
     * @return the value of doll_users.is_lock
     *
     * @mbggenerated
     */
    public Boolean getIsLock() {
        return isLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_users.is_lock
     *
     * @param isLock the value for doll_users.is_lock
     *
     * @mbggenerated
     */
    public void setIsLock(Boolean isLock) {
        this.isLock = isLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_users.is_distribut
     *
     * @return the value of doll_users.is_distribut
     *
     * @mbggenerated
     */
    public Boolean getIsDistribut() {
        return isDistribut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_users.is_distribut
     *
     * @param isDistribut the value for doll_users.is_distribut
     *
     * @mbggenerated
     */
    public void setIsDistribut(Boolean isDistribut) {
        this.isDistribut = isDistribut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_users.first_leader
     *
     * @return the value of doll_users.first_leader
     *
     * @mbggenerated
     */
    public Integer getFirstLeader() {
        return firstLeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_users.first_leader
     *
     * @param firstLeader the value for doll_users.first_leader
     *
     * @mbggenerated
     */
    public void setFirstLeader(Integer firstLeader) {
        this.firstLeader = firstLeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_users.second_leader
     *
     * @return the value of doll_users.second_leader
     *
     * @mbggenerated
     */
    public Integer getSecondLeader() {
        return secondLeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_users.second_leader
     *
     * @param secondLeader the value for doll_users.second_leader
     *
     * @mbggenerated
     */
    public void setSecondLeader(Integer secondLeader) {
        this.secondLeader = secondLeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_users.third_leader
     *
     * @return the value of doll_users.third_leader
     *
     * @mbggenerated
     */
    public Integer getThirdLeader() {
        return thirdLeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_users.third_leader
     *
     * @param thirdLeader the value for doll_users.third_leader
     *
     * @mbggenerated
     */
    public void setThirdLeader(Integer thirdLeader) {
        this.thirdLeader = thirdLeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_users.token
     *
     * @return the value of doll_users.token
     *
     * @mbggenerated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_users.token
     *
     * @param token the value for doll_users.token
     *
     * @mbggenerated
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doll_users
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", email=").append(email);
        sb.append(", password=").append(password);
        sb.append(", sex=").append(sex);
        sb.append(", birthday=").append(birthday);
        sb.append(", userMoney=").append(userMoney);
        sb.append(", frozenMoney=").append(frozenMoney);
        sb.append(", distributMoney=").append(distributMoney);
        sb.append(", payPoints=").append(payPoints);
        sb.append(", addressId=").append(addressId);
        sb.append(", regTime=").append(regTime);
        sb.append(", lastLogin=").append(lastLogin);
        sb.append(", lastIp=").append(lastIp);
        sb.append(", qq=").append(qq);
        sb.append(", mobile=").append(mobile);
        sb.append(", mobileValidated=").append(mobileValidated);
        sb.append(", oauth=").append(oauth);
        sb.append(", openid=").append(openid);
        sb.append(", headPic=").append(headPic);
        sb.append(", province=").append(province);
        sb.append(", city=").append(city);
        sb.append(", district=").append(district);
        sb.append(", emailValidated=").append(emailValidated);
        sb.append(", nickname=").append(nickname);
        sb.append(", level=").append(level);
        sb.append(", discount=").append(discount);
        sb.append(", totalAmount=").append(totalAmount);
        sb.append(", isLock=").append(isLock);
        sb.append(", isDistribut=").append(isDistribut);
        sb.append(", firstLeader=").append(firstLeader);
        sb.append(", secondLeader=").append(secondLeader);
        sb.append(", thirdLeader=").append(thirdLeader);
        sb.append(", token=").append(token);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}