package com.aotubuy.Model;

import java.io.Serializable;
import java.math.BigDecimal;

public class DollCart implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_cart.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_cart.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_cart.session_id
     *
     * @mbggenerated
     */
    private String sessionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_cart.goods_id
     *
     * @mbggenerated
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_cart.goods_sn
     *
     * @mbggenerated
     */
    private String goodsSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_cart.goods_name
     *
     * @mbggenerated
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_cart.market_price
     *
     * @mbggenerated
     */
    private BigDecimal marketPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_cart.goods_price
     *
     * @mbggenerated
     */
    private BigDecimal goodsPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_cart.member_goods_price
     *
     * @mbggenerated
     */
    private BigDecimal memberGoodsPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_cart.goods_num
     *
     * @mbggenerated
     */
    private Short goodsNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_cart.spec_key
     *
     * @mbggenerated
     */
    private String specKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_cart.spec_key_name
     *
     * @mbggenerated
     */
    private String specKeyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_cart.bar_code
     *
     * @mbggenerated
     */
    private String barCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_cart.selected
     *
     * @mbggenerated
     */
    private Boolean selected;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_cart.add_time
     *
     * @mbggenerated
     */
    private Integer addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_cart.prom_type
     *
     * @mbggenerated
     */
    private Boolean promType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_cart.prom_id
     *
     * @mbggenerated
     */
    private Integer promId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_cart.sku
     *
     * @mbggenerated
     */
    private String sku;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table doll_cart
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_cart.id
     *
     * @return the value of doll_cart.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_cart.id
     *
     * @param id the value for doll_cart.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_cart.user_id
     *
     * @return the value of doll_cart.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_cart.user_id
     *
     * @param userId the value for doll_cart.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_cart.session_id
     *
     * @return the value of doll_cart.session_id
     *
     * @mbggenerated
     */
    public String getSessionId() {
        return sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_cart.session_id
     *
     * @param sessionId the value for doll_cart.session_id
     *
     * @mbggenerated
     */
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId == null ? null : sessionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_cart.goods_id
     *
     * @return the value of doll_cart.goods_id
     *
     * @mbggenerated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_cart.goods_id
     *
     * @param goodsId the value for doll_cart.goods_id
     *
     * @mbggenerated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_cart.goods_sn
     *
     * @return the value of doll_cart.goods_sn
     *
     * @mbggenerated
     */
    public String getGoodsSn() {
        return goodsSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_cart.goods_sn
     *
     * @param goodsSn the value for doll_cart.goods_sn
     *
     * @mbggenerated
     */
    public void setGoodsSn(String goodsSn) {
        this.goodsSn = goodsSn == null ? null : goodsSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_cart.goods_name
     *
     * @return the value of doll_cart.goods_name
     *
     * @mbggenerated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_cart.goods_name
     *
     * @param goodsName the value for doll_cart.goods_name
     *
     * @mbggenerated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_cart.market_price
     *
     * @return the value of doll_cart.market_price
     *
     * @mbggenerated
     */
    public BigDecimal getMarketPrice() {
        return marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_cart.market_price
     *
     * @param marketPrice the value for doll_cart.market_price
     *
     * @mbggenerated
     */
    public void setMarketPrice(BigDecimal marketPrice) {
        this.marketPrice = marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_cart.goods_price
     *
     * @return the value of doll_cart.goods_price
     *
     * @mbggenerated
     */
    public BigDecimal getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_cart.goods_price
     *
     * @param goodsPrice the value for doll_cart.goods_price
     *
     * @mbggenerated
     */
    public void setGoodsPrice(BigDecimal goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_cart.member_goods_price
     *
     * @return the value of doll_cart.member_goods_price
     *
     * @mbggenerated
     */
    public BigDecimal getMemberGoodsPrice() {
        return memberGoodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_cart.member_goods_price
     *
     * @param memberGoodsPrice the value for doll_cart.member_goods_price
     *
     * @mbggenerated
     */
    public void setMemberGoodsPrice(BigDecimal memberGoodsPrice) {
        this.memberGoodsPrice = memberGoodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_cart.goods_num
     *
     * @return the value of doll_cart.goods_num
     *
     * @mbggenerated
     */
    public Short getGoodsNum() {
        return goodsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_cart.goods_num
     *
     * @param goodsNum the value for doll_cart.goods_num
     *
     * @mbggenerated
     */
    public void setGoodsNum(Short goodsNum) {
        this.goodsNum = goodsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_cart.spec_key
     *
     * @return the value of doll_cart.spec_key
     *
     * @mbggenerated
     */
    public String getSpecKey() {
        return specKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_cart.spec_key
     *
     * @param specKey the value for doll_cart.spec_key
     *
     * @mbggenerated
     */
    public void setSpecKey(String specKey) {
        this.specKey = specKey == null ? null : specKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_cart.spec_key_name
     *
     * @return the value of doll_cart.spec_key_name
     *
     * @mbggenerated
     */
    public String getSpecKeyName() {
        return specKeyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_cart.spec_key_name
     *
     * @param specKeyName the value for doll_cart.spec_key_name
     *
     * @mbggenerated
     */
    public void setSpecKeyName(String specKeyName) {
        this.specKeyName = specKeyName == null ? null : specKeyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_cart.bar_code
     *
     * @return the value of doll_cart.bar_code
     *
     * @mbggenerated
     */
    public String getBarCode() {
        return barCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_cart.bar_code
     *
     * @param barCode the value for doll_cart.bar_code
     *
     * @mbggenerated
     */
    public void setBarCode(String barCode) {
        this.barCode = barCode == null ? null : barCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_cart.selected
     *
     * @return the value of doll_cart.selected
     *
     * @mbggenerated
     */
    public Boolean getSelected() {
        return selected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_cart.selected
     *
     * @param selected the value for doll_cart.selected
     *
     * @mbggenerated
     */
    public void setSelected(Boolean selected) {
        this.selected = selected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_cart.add_time
     *
     * @return the value of doll_cart.add_time
     *
     * @mbggenerated
     */
    public Integer getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_cart.add_time
     *
     * @param addTime the value for doll_cart.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Integer addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_cart.prom_type
     *
     * @return the value of doll_cart.prom_type
     *
     * @mbggenerated
     */
    public Boolean getPromType() {
        return promType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_cart.prom_type
     *
     * @param promType the value for doll_cart.prom_type
     *
     * @mbggenerated
     */
    public void setPromType(Boolean promType) {
        this.promType = promType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_cart.prom_id
     *
     * @return the value of doll_cart.prom_id
     *
     * @mbggenerated
     */
    public Integer getPromId() {
        return promId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_cart.prom_id
     *
     * @param promId the value for doll_cart.prom_id
     *
     * @mbggenerated
     */
    public void setPromId(Integer promId) {
        this.promId = promId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_cart.sku
     *
     * @return the value of doll_cart.sku
     *
     * @mbggenerated
     */
    public String getSku() {
        return sku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_cart.sku
     *
     * @param sku the value for doll_cart.sku
     *
     * @mbggenerated
     */
    public void setSku(String sku) {
        this.sku = sku == null ? null : sku.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doll_cart
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", sessionId=").append(sessionId);
        sb.append(", goodsId=").append(goodsId);
        sb.append(", goodsSn=").append(goodsSn);
        sb.append(", goodsName=").append(goodsName);
        sb.append(", marketPrice=").append(marketPrice);
        sb.append(", goodsPrice=").append(goodsPrice);
        sb.append(", memberGoodsPrice=").append(memberGoodsPrice);
        sb.append(", goodsNum=").append(goodsNum);
        sb.append(", specKey=").append(specKey);
        sb.append(", specKeyName=").append(specKeyName);
        sb.append(", barCode=").append(barCode);
        sb.append(", selected=").append(selected);
        sb.append(", addTime=").append(addTime);
        sb.append(", promType=").append(promType);
        sb.append(", promId=").append(promId);
        sb.append(", sku=").append(sku);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}