package com.aotubuy.Model;

import java.io.Serializable;

public class DollAdPosition implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_ad_position.position_id
     *
     * @mbggenerated
     */
    private Integer positionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_ad_position.position_name
     *
     * @mbggenerated
     */
    private String positionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_ad_position.ad_width
     *
     * @mbggenerated
     */
    private Short adWidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_ad_position.ad_height
     *
     * @mbggenerated
     */
    private Short adHeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_ad_position.position_desc
     *
     * @mbggenerated
     */
    private String positionDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_ad_position.is_open
     *
     * @mbggenerated
     */
    private Boolean isOpen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doll_ad_position.position_style
     *
     * @mbggenerated
     */
    private String positionStyle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table doll_ad_position
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_ad_position.position_id
     *
     * @return the value of doll_ad_position.position_id
     *
     * @mbggenerated
     */
    public Integer getPositionId() {
        return positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_ad_position.position_id
     *
     * @param positionId the value for doll_ad_position.position_id
     *
     * @mbggenerated
     */
    public void setPositionId(Integer positionId) {
        this.positionId = positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_ad_position.position_name
     *
     * @return the value of doll_ad_position.position_name
     *
     * @mbggenerated
     */
    public String getPositionName() {
        return positionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_ad_position.position_name
     *
     * @param positionName the value for doll_ad_position.position_name
     *
     * @mbggenerated
     */
    public void setPositionName(String positionName) {
        this.positionName = positionName == null ? null : positionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_ad_position.ad_width
     *
     * @return the value of doll_ad_position.ad_width
     *
     * @mbggenerated
     */
    public Short getAdWidth() {
        return adWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_ad_position.ad_width
     *
     * @param adWidth the value for doll_ad_position.ad_width
     *
     * @mbggenerated
     */
    public void setAdWidth(Short adWidth) {
        this.adWidth = adWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_ad_position.ad_height
     *
     * @return the value of doll_ad_position.ad_height
     *
     * @mbggenerated
     */
    public Short getAdHeight() {
        return adHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_ad_position.ad_height
     *
     * @param adHeight the value for doll_ad_position.ad_height
     *
     * @mbggenerated
     */
    public void setAdHeight(Short adHeight) {
        this.adHeight = adHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_ad_position.position_desc
     *
     * @return the value of doll_ad_position.position_desc
     *
     * @mbggenerated
     */
    public String getPositionDesc() {
        return positionDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_ad_position.position_desc
     *
     * @param positionDesc the value for doll_ad_position.position_desc
     *
     * @mbggenerated
     */
    public void setPositionDesc(String positionDesc) {
        this.positionDesc = positionDesc == null ? null : positionDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_ad_position.is_open
     *
     * @return the value of doll_ad_position.is_open
     *
     * @mbggenerated
     */
    public Boolean getIsOpen() {
        return isOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_ad_position.is_open
     *
     * @param isOpen the value for doll_ad_position.is_open
     *
     * @mbggenerated
     */
    public void setIsOpen(Boolean isOpen) {
        this.isOpen = isOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doll_ad_position.position_style
     *
     * @return the value of doll_ad_position.position_style
     *
     * @mbggenerated
     */
    public String getPositionStyle() {
        return positionStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doll_ad_position.position_style
     *
     * @param positionStyle the value for doll_ad_position.position_style
     *
     * @mbggenerated
     */
    public void setPositionStyle(String positionStyle) {
        this.positionStyle = positionStyle == null ? null : positionStyle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doll_ad_position
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", positionId=").append(positionId);
        sb.append(", positionName=").append(positionName);
        sb.append(", adWidth=").append(adWidth);
        sb.append(", adHeight=").append(adHeight);
        sb.append(", positionDesc=").append(positionDesc);
        sb.append(", isOpen=").append(isOpen);
        sb.append(", positionStyle=").append(positionStyle);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}