package com.aotubuy.Model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class TActivityType implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity_type.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity_type.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity_type.sub_title
     *
     * @mbggenerated
     */
    private String subTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity_type.pay_type
     *
     * @mbggenerated
     */
    private Integer payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity_type.detail_img
     *
     * @mbggenerated
     */
    private String detailImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity_type.list_img
     *
     * @mbggenerated
     */
    private String listImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity_type.applicable_people
     *
     * @mbggenerated
     */
    private String applicablePeople;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity_type.specific_location
     *
     * @mbggenerated
     */
    private String specificLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity_type.expense_detail
     *
     * @mbggenerated
     */
    private String expenseDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity_type.preparation
     *
     * @mbggenerated
     */
    private String preparation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity_type.hot_sale
     *
     * @mbggenerated
     */
    private Boolean hotSale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity_type.recommend
     *
     * @mbggenerated
     */
    private Boolean recommend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity_type.new_sale
     *
     * @mbggenerated
     */
    private Boolean newSale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity_type.enable
     *
     * @mbggenerated
     */
    private Boolean enable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity_type.exclusive
     *
     * @mbggenerated
     */
    private Boolean exclusive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity_type.on_sale
     *
     * @mbggenerated
     */
    private Boolean onSale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity_type.activity_location
     *
     * @mbggenerated
     */
    private String activityLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity_type.location_range
     *
     * @mbggenerated
     */
    private String locationRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity_type.form
     *
     * @mbggenerated
     */
    private Integer form;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity_type.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity_type.upper_and_lower_time
     *
     * @mbggenerated
     */
    private Date upperAndLowerTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity_type.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity_type.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity_type.modifier
     *
     * @mbggenerated
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity_type.level
     *
     * @mbggenerated
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity_type.sale_num
     *
     * @mbggenerated
     */
    private Integer saleNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity_type.view_num
     *
     * @mbggenerated
     */
    private Integer viewNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity_type.mini_price
     *
     * @mbggenerated
     */
    private BigDecimal miniPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity_type.presell
     *
     * @mbggenerated
     */
    private Boolean presell;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity_type.complete_type
     *
     * @mbggenerated
     */
    private Integer completeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity_type.presell_content
     *
     * @mbggenerated
     */
    private String presellContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_activity_type
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_type.id
     *
     * @return the value of t_activity_type.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_type.id
     *
     * @param id the value for t_activity_type.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_type.title
     *
     * @return the value of t_activity_type.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_type.title
     *
     * @param title the value for t_activity_type.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_type.sub_title
     *
     * @return the value of t_activity_type.sub_title
     *
     * @mbggenerated
     */
    public String getSubTitle() {
        return subTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_type.sub_title
     *
     * @param subTitle the value for t_activity_type.sub_title
     *
     * @mbggenerated
     */
    public void setSubTitle(String subTitle) {
        this.subTitle = subTitle == null ? null : subTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_type.pay_type
     *
     * @return the value of t_activity_type.pay_type
     *
     * @mbggenerated
     */
    public Integer getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_type.pay_type
     *
     * @param payType the value for t_activity_type.pay_type
     *
     * @mbggenerated
     */
    public void setPayType(Integer payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_type.detail_img
     *
     * @return the value of t_activity_type.detail_img
     *
     * @mbggenerated
     */
    public String getDetailImg() {
        return detailImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_type.detail_img
     *
     * @param detailImg the value for t_activity_type.detail_img
     *
     * @mbggenerated
     */
    public void setDetailImg(String detailImg) {
        this.detailImg = detailImg == null ? null : detailImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_type.list_img
     *
     * @return the value of t_activity_type.list_img
     *
     * @mbggenerated
     */
    public String getListImg() {
        return listImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_type.list_img
     *
     * @param listImg the value for t_activity_type.list_img
     *
     * @mbggenerated
     */
    public void setListImg(String listImg) {
        this.listImg = listImg == null ? null : listImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_type.applicable_people
     *
     * @return the value of t_activity_type.applicable_people
     *
     * @mbggenerated
     */
    public String getApplicablePeople() {
        return applicablePeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_type.applicable_people
     *
     * @param applicablePeople the value for t_activity_type.applicable_people
     *
     * @mbggenerated
     */
    public void setApplicablePeople(String applicablePeople) {
        this.applicablePeople = applicablePeople == null ? null : applicablePeople.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_type.specific_location
     *
     * @return the value of t_activity_type.specific_location
     *
     * @mbggenerated
     */
    public String getSpecificLocation() {
        return specificLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_type.specific_location
     *
     * @param specificLocation the value for t_activity_type.specific_location
     *
     * @mbggenerated
     */
    public void setSpecificLocation(String specificLocation) {
        this.specificLocation = specificLocation == null ? null : specificLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_type.expense_detail
     *
     * @return the value of t_activity_type.expense_detail
     *
     * @mbggenerated
     */
    public String getExpenseDetail() {
        return expenseDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_type.expense_detail
     *
     * @param expenseDetail the value for t_activity_type.expense_detail
     *
     * @mbggenerated
     */
    public void setExpenseDetail(String expenseDetail) {
        this.expenseDetail = expenseDetail == null ? null : expenseDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_type.preparation
     *
     * @return the value of t_activity_type.preparation
     *
     * @mbggenerated
     */
    public String getPreparation() {
        return preparation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_type.preparation
     *
     * @param preparation the value for t_activity_type.preparation
     *
     * @mbggenerated
     */
    public void setPreparation(String preparation) {
        this.preparation = preparation == null ? null : preparation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_type.hot_sale
     *
     * @return the value of t_activity_type.hot_sale
     *
     * @mbggenerated
     */
    public Boolean getHotSale() {
        return hotSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_type.hot_sale
     *
     * @param hotSale the value for t_activity_type.hot_sale
     *
     * @mbggenerated
     */
    public void setHotSale(Boolean hotSale) {
        this.hotSale = hotSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_type.recommend
     *
     * @return the value of t_activity_type.recommend
     *
     * @mbggenerated
     */
    public Boolean getRecommend() {
        return recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_type.recommend
     *
     * @param recommend the value for t_activity_type.recommend
     *
     * @mbggenerated
     */
    public void setRecommend(Boolean recommend) {
        this.recommend = recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_type.new_sale
     *
     * @return the value of t_activity_type.new_sale
     *
     * @mbggenerated
     */
    public Boolean getNewSale() {
        return newSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_type.new_sale
     *
     * @param newSale the value for t_activity_type.new_sale
     *
     * @mbggenerated
     */
    public void setNewSale(Boolean newSale) {
        this.newSale = newSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_type.enable
     *
     * @return the value of t_activity_type.enable
     *
     * @mbggenerated
     */
    public Boolean getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_type.enable
     *
     * @param enable the value for t_activity_type.enable
     *
     * @mbggenerated
     */
    public void setEnable(Boolean enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_type.exclusive
     *
     * @return the value of t_activity_type.exclusive
     *
     * @mbggenerated
     */
    public Boolean getExclusive() {
        return exclusive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_type.exclusive
     *
     * @param exclusive the value for t_activity_type.exclusive
     *
     * @mbggenerated
     */
    public void setExclusive(Boolean exclusive) {
        this.exclusive = exclusive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_type.on_sale
     *
     * @return the value of t_activity_type.on_sale
     *
     * @mbggenerated
     */
    public Boolean getOnSale() {
        return onSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_type.on_sale
     *
     * @param onSale the value for t_activity_type.on_sale
     *
     * @mbggenerated
     */
    public void setOnSale(Boolean onSale) {
        this.onSale = onSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_type.activity_location
     *
     * @return the value of t_activity_type.activity_location
     *
     * @mbggenerated
     */
    public String getActivityLocation() {
        return activityLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_type.activity_location
     *
     * @param activityLocation the value for t_activity_type.activity_location
     *
     * @mbggenerated
     */
    public void setActivityLocation(String activityLocation) {
        this.activityLocation = activityLocation == null ? null : activityLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_type.location_range
     *
     * @return the value of t_activity_type.location_range
     *
     * @mbggenerated
     */
    public String getLocationRange() {
        return locationRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_type.location_range
     *
     * @param locationRange the value for t_activity_type.location_range
     *
     * @mbggenerated
     */
    public void setLocationRange(String locationRange) {
        this.locationRange = locationRange == null ? null : locationRange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_type.form
     *
     * @return the value of t_activity_type.form
     *
     * @mbggenerated
     */
    public Integer getForm() {
        return form;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_type.form
     *
     * @param form the value for t_activity_type.form
     *
     * @mbggenerated
     */
    public void setForm(Integer form) {
        this.form = form;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_type.create_time
     *
     * @return the value of t_activity_type.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_type.create_time
     *
     * @param createTime the value for t_activity_type.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_type.upper_and_lower_time
     *
     * @return the value of t_activity_type.upper_and_lower_time
     *
     * @mbggenerated
     */
    public Date getUpperAndLowerTime() {
        return upperAndLowerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_type.upper_and_lower_time
     *
     * @param upperAndLowerTime the value for t_activity_type.upper_and_lower_time
     *
     * @mbggenerated
     */
    public void setUpperAndLowerTime(Date upperAndLowerTime) {
        this.upperAndLowerTime = upperAndLowerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_type.modify_time
     *
     * @return the value of t_activity_type.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_type.modify_time
     *
     * @param modifyTime the value for t_activity_type.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_type.creator
     *
     * @return the value of t_activity_type.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_type.creator
     *
     * @param creator the value for t_activity_type.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_type.modifier
     *
     * @return the value of t_activity_type.modifier
     *
     * @mbggenerated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_type.modifier
     *
     * @param modifier the value for t_activity_type.modifier
     *
     * @mbggenerated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_type.level
     *
     * @return the value of t_activity_type.level
     *
     * @mbggenerated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_type.level
     *
     * @param level the value for t_activity_type.level
     *
     * @mbggenerated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_type.sale_num
     *
     * @return the value of t_activity_type.sale_num
     *
     * @mbggenerated
     */
    public Integer getSaleNum() {
        return saleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_type.sale_num
     *
     * @param saleNum the value for t_activity_type.sale_num
     *
     * @mbggenerated
     */
    public void setSaleNum(Integer saleNum) {
        this.saleNum = saleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_type.view_num
     *
     * @return the value of t_activity_type.view_num
     *
     * @mbggenerated
     */
    public Integer getViewNum() {
        return viewNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_type.view_num
     *
     * @param viewNum the value for t_activity_type.view_num
     *
     * @mbggenerated
     */
    public void setViewNum(Integer viewNum) {
        this.viewNum = viewNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_type.mini_price
     *
     * @return the value of t_activity_type.mini_price
     *
     * @mbggenerated
     */
    public BigDecimal getMiniPrice() {
        return miniPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_type.mini_price
     *
     * @param miniPrice the value for t_activity_type.mini_price
     *
     * @mbggenerated
     */
    public void setMiniPrice(BigDecimal miniPrice) {
        this.miniPrice = miniPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_type.presell
     *
     * @return the value of t_activity_type.presell
     *
     * @mbggenerated
     */
    public Boolean getPresell() {
        return presell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_type.presell
     *
     * @param presell the value for t_activity_type.presell
     *
     * @mbggenerated
     */
    public void setPresell(Boolean presell) {
        this.presell = presell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_type.complete_type
     *
     * @return the value of t_activity_type.complete_type
     *
     * @mbggenerated
     */
    public Integer getCompleteType() {
        return completeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_type.complete_type
     *
     * @param completeType the value for t_activity_type.complete_type
     *
     * @mbggenerated
     */
    public void setCompleteType(Integer completeType) {
        this.completeType = completeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_type.presell_content
     *
     * @return the value of t_activity_type.presell_content
     *
     * @mbggenerated
     */
    public String getPresellContent() {
        return presellContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_type.presell_content
     *
     * @param presellContent the value for t_activity_type.presell_content
     *
     * @mbggenerated
     */
    public void setPresellContent(String presellContent) {
        this.presellContent = presellContent == null ? null : presellContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_type
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", title=").append(title);
        sb.append(", subTitle=").append(subTitle);
        sb.append(", payType=").append(payType);
        sb.append(", detailImg=").append(detailImg);
        sb.append(", listImg=").append(listImg);
        sb.append(", applicablePeople=").append(applicablePeople);
        sb.append(", specificLocation=").append(specificLocation);
        sb.append(", expenseDetail=").append(expenseDetail);
        sb.append(", preparation=").append(preparation);
        sb.append(", hotSale=").append(hotSale);
        sb.append(", recommend=").append(recommend);
        sb.append(", newSale=").append(newSale);
        sb.append(", enable=").append(enable);
        sb.append(", exclusive=").append(exclusive);
        sb.append(", onSale=").append(onSale);
        sb.append(", activityLocation=").append(activityLocation);
        sb.append(", locationRange=").append(locationRange);
        sb.append(", form=").append(form);
        sb.append(", createTime=").append(createTime);
        sb.append(", upperAndLowerTime=").append(upperAndLowerTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", creator=").append(creator);
        sb.append(", modifier=").append(modifier);
        sb.append(", level=").append(level);
        sb.append(", saleNum=").append(saleNum);
        sb.append(", viewNum=").append(viewNum);
        sb.append(", miniPrice=").append(miniPrice);
        sb.append(", presell=").append(presell);
        sb.append(", completeType=").append(completeType);
        sb.append(", presellContent=").append(presellContent);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}