package com.aotubuy.Model;

import java.io.Serializable;

public class TCouponProduct implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon_product.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon_product.coupon_type_id
     *
     * @mbggenerated
     */
    private String couponTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon_product.product_id
     *
     * @mbggenerated
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon_product.product_name
     *
     * @mbggenerated
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon_product.coupon_type_name
     *
     * @mbggenerated
     */
    private String couponTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_coupon_product
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon_product.id
     *
     * @return the value of t_coupon_product.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon_product.id
     *
     * @param id the value for t_coupon_product.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon_product.coupon_type_id
     *
     * @return the value of t_coupon_product.coupon_type_id
     *
     * @mbggenerated
     */
    public String getCouponTypeId() {
        return couponTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon_product.coupon_type_id
     *
     * @param couponTypeId the value for t_coupon_product.coupon_type_id
     *
     * @mbggenerated
     */
    public void setCouponTypeId(String couponTypeId) {
        this.couponTypeId = couponTypeId == null ? null : couponTypeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon_product.product_id
     *
     * @return the value of t_coupon_product.product_id
     *
     * @mbggenerated
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon_product.product_id
     *
     * @param productId the value for t_coupon_product.product_id
     *
     * @mbggenerated
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon_product.product_name
     *
     * @return the value of t_coupon_product.product_name
     *
     * @mbggenerated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon_product.product_name
     *
     * @param productName the value for t_coupon_product.product_name
     *
     * @mbggenerated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon_product.coupon_type_name
     *
     * @return the value of t_coupon_product.coupon_type_name
     *
     * @mbggenerated
     */
    public String getCouponTypeName() {
        return couponTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon_product.coupon_type_name
     *
     * @param couponTypeName the value for t_coupon_product.coupon_type_name
     *
     * @mbggenerated
     */
    public void setCouponTypeName(String couponTypeName) {
        this.couponTypeName = couponTypeName == null ? null : couponTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon_product
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", couponTypeId=").append(couponTypeId);
        sb.append(", productId=").append(productId);
        sb.append(", productName=").append(productName);
        sb.append(", couponTypeName=").append(couponTypeName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}