package com.aotubuy.Model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class TCoupon implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon.discount_type
     *
     * @mbggenerated
     */
    private Integer discountType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon.discount
     *
     * @mbggenerated
     */
    private Double discount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon.condition
     *
     * @mbggenerated
     */
    private BigDecimal condition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon.use_start_time
     *
     * @mbggenerated
     */
    private Date useStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon.use_end_time
     *
     * @mbggenerated
     */
    private Date useEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon.create_num
     *
     * @mbggenerated
     */
    private Long createNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon.send_num
     *
     * @mbggenerated
     */
    private Long sendNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon.use_num
     *
     * @mbggenerated
     */
    private Long useNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon.enable
     *
     * @mbggenerated
     */
    private Boolean enable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_coupon
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon.id
     *
     * @return the value of t_coupon.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon.id
     *
     * @param id the value for t_coupon.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon.name
     *
     * @return the value of t_coupon.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon.name
     *
     * @param name the value for t_coupon.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon.description
     *
     * @return the value of t_coupon.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon.description
     *
     * @param description the value for t_coupon.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon.discount_type
     *
     * @return the value of t_coupon.discount_type
     *
     * @mbggenerated
     */
    public Integer getDiscountType() {
        return discountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon.discount_type
     *
     * @param discountType the value for t_coupon.discount_type
     *
     * @mbggenerated
     */
    public void setDiscountType(Integer discountType) {
        this.discountType = discountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon.discount
     *
     * @return the value of t_coupon.discount
     *
     * @mbggenerated
     */
    public Double getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon.discount
     *
     * @param discount the value for t_coupon.discount
     *
     * @mbggenerated
     */
    public void setDiscount(Double discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon.condition
     *
     * @return the value of t_coupon.condition
     *
     * @mbggenerated
     */
    public BigDecimal getCondition() {
        return condition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon.condition
     *
     * @param condition the value for t_coupon.condition
     *
     * @mbggenerated
     */
    public void setCondition(BigDecimal condition) {
        this.condition = condition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon.use_start_time
     *
     * @return the value of t_coupon.use_start_time
     *
     * @mbggenerated
     */
    public Date getUseStartTime() {
        return useStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon.use_start_time
     *
     * @param useStartTime the value for t_coupon.use_start_time
     *
     * @mbggenerated
     */
    public void setUseStartTime(Date useStartTime) {
        this.useStartTime = useStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon.use_end_time
     *
     * @return the value of t_coupon.use_end_time
     *
     * @mbggenerated
     */
    public Date getUseEndTime() {
        return useEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon.use_end_time
     *
     * @param useEndTime the value for t_coupon.use_end_time
     *
     * @mbggenerated
     */
    public void setUseEndTime(Date useEndTime) {
        this.useEndTime = useEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon.create_num
     *
     * @return the value of t_coupon.create_num
     *
     * @mbggenerated
     */
    public Long getCreateNum() {
        return createNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon.create_num
     *
     * @param createNum the value for t_coupon.create_num
     *
     * @mbggenerated
     */
    public void setCreateNum(Long createNum) {
        this.createNum = createNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon.send_num
     *
     * @return the value of t_coupon.send_num
     *
     * @mbggenerated
     */
    public Long getSendNum() {
        return sendNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon.send_num
     *
     * @param sendNum the value for t_coupon.send_num
     *
     * @mbggenerated
     */
    public void setSendNum(Long sendNum) {
        this.sendNum = sendNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon.use_num
     *
     * @return the value of t_coupon.use_num
     *
     * @mbggenerated
     */
    public Long getUseNum() {
        return useNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon.use_num
     *
     * @param useNum the value for t_coupon.use_num
     *
     * @mbggenerated
     */
    public void setUseNum(Long useNum) {
        this.useNum = useNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon.enable
     *
     * @return the value of t_coupon.enable
     *
     * @mbggenerated
     */
    public Boolean getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon.enable
     *
     * @param enable the value for t_coupon.enable
     *
     * @mbggenerated
     */
    public void setEnable(Boolean enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", description=").append(description);
        sb.append(", discountType=").append(discountType);
        sb.append(", discount=").append(discount);
        sb.append(", condition=").append(condition);
        sb.append(", useStartTime=").append(useStartTime);
        sb.append(", useEndTime=").append(useEndTime);
        sb.append(", createNum=").append(createNum);
        sb.append(", sendNum=").append(sendNum);
        sb.append(", useNum=").append(useNum);
        sb.append(", enable=").append(enable);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}