package com.aotubuy.Model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class TpOrder implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.order_no
     *
     * @mbggenerated
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.product_name
     *
     * @mbggenerated
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.uid
     *
     * @mbggenerated
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.product_id
     *
     * @mbggenerated
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.order_detail_id
     *
     * @mbggenerated
     */
    private String orderDetailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.product_type
     *
     * @mbggenerated
     */
    private Integer productType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.product_level
     *
     * @mbggenerated
     */
    private Integer productLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.order_amount
     *
     * @mbggenerated
     */
    private BigDecimal orderAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.discount_amount
     *
     * @mbggenerated
     */
    private BigDecimal discountAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.final_amount
     *
     * @mbggenerated
     */
    private BigDecimal finalAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.refund_amount
     *
     * @mbggenerated
     */
    private BigDecimal refundAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.pay_type
     *
     * @mbggenerated
     */
    private String payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.pay_no
     *
     * @mbggenerated
     */
    private String payNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.pay_time
     *
     * @mbggenerated
     */
    private Date payTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.cancel_time
     *
     * @mbggenerated
     */
    private Date cancelTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.refund_time
     *
     * @mbggenerated
     */
    private Date refundTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.is_receipt
     *
     * @mbggenerated
     */
    private Integer isReceipt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.num
     *
     * @mbggenerated
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.act_id
     *
     * @mbggenerated
     */
    private String actId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.ref_id
     *
     * @mbggenerated
     */
    private String refId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.is_bill
     *
     * @mbggenerated
     */
    private Integer isBill;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_order
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.order_no
     *
     * @return the value of tp_order.order_no
     *
     * @mbggenerated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.order_no
     *
     * @param orderNo the value for tp_order.order_no
     *
     * @mbggenerated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.product_name
     *
     * @return the value of tp_order.product_name
     *
     * @mbggenerated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.product_name
     *
     * @param productName the value for tp_order.product_name
     *
     * @mbggenerated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.uid
     *
     * @return the value of tp_order.uid
     *
     * @mbggenerated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.uid
     *
     * @param uid the value for tp_order.uid
     *
     * @mbggenerated
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.user_name
     *
     * @return the value of tp_order.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.user_name
     *
     * @param userName the value for tp_order.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.mobile
     *
     * @return the value of tp_order.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.mobile
     *
     * @param mobile the value for tp_order.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.product_id
     *
     * @return the value of tp_order.product_id
     *
     * @mbggenerated
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.product_id
     *
     * @param productId the value for tp_order.product_id
     *
     * @mbggenerated
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.order_detail_id
     *
     * @return the value of tp_order.order_detail_id
     *
     * @mbggenerated
     */
    public String getOrderDetailId() {
        return orderDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.order_detail_id
     *
     * @param orderDetailId the value for tp_order.order_detail_id
     *
     * @mbggenerated
     */
    public void setOrderDetailId(String orderDetailId) {
        this.orderDetailId = orderDetailId == null ? null : orderDetailId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.product_type
     *
     * @return the value of tp_order.product_type
     *
     * @mbggenerated
     */
    public Integer getProductType() {
        return productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.product_type
     *
     * @param productType the value for tp_order.product_type
     *
     * @mbggenerated
     */
    public void setProductType(Integer productType) {
        this.productType = productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.product_level
     *
     * @return the value of tp_order.product_level
     *
     * @mbggenerated
     */
    public Integer getProductLevel() {
        return productLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.product_level
     *
     * @param productLevel the value for tp_order.product_level
     *
     * @mbggenerated
     */
    public void setProductLevel(Integer productLevel) {
        this.productLevel = productLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.order_amount
     *
     * @return the value of tp_order.order_amount
     *
     * @mbggenerated
     */
    public BigDecimal getOrderAmount() {
        return orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.order_amount
     *
     * @param orderAmount the value for tp_order.order_amount
     *
     * @mbggenerated
     */
    public void setOrderAmount(BigDecimal orderAmount) {
        this.orderAmount = orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.discount_amount
     *
     * @return the value of tp_order.discount_amount
     *
     * @mbggenerated
     */
    public BigDecimal getDiscountAmount() {
        return discountAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.discount_amount
     *
     * @param discountAmount the value for tp_order.discount_amount
     *
     * @mbggenerated
     */
    public void setDiscountAmount(BigDecimal discountAmount) {
        this.discountAmount = discountAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.final_amount
     *
     * @return the value of tp_order.final_amount
     *
     * @mbggenerated
     */
    public BigDecimal getFinalAmount() {
        return finalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.final_amount
     *
     * @param finalAmount the value for tp_order.final_amount
     *
     * @mbggenerated
     */
    public void setFinalAmount(BigDecimal finalAmount) {
        this.finalAmount = finalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.refund_amount
     *
     * @return the value of tp_order.refund_amount
     *
     * @mbggenerated
     */
    public BigDecimal getRefundAmount() {
        return refundAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.refund_amount
     *
     * @param refundAmount the value for tp_order.refund_amount
     *
     * @mbggenerated
     */
    public void setRefundAmount(BigDecimal refundAmount) {
        this.refundAmount = refundAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.create_time
     *
     * @return the value of tp_order.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.create_time
     *
     * @param createTime the value for tp_order.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.status
     *
     * @return the value of tp_order.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.status
     *
     * @param status the value for tp_order.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.pay_type
     *
     * @return the value of tp_order.pay_type
     *
     * @mbggenerated
     */
    public String getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.pay_type
     *
     * @param payType the value for tp_order.pay_type
     *
     * @mbggenerated
     */
    public void setPayType(String payType) {
        this.payType = payType == null ? null : payType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.pay_no
     *
     * @return the value of tp_order.pay_no
     *
     * @mbggenerated
     */
    public String getPayNo() {
        return payNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.pay_no
     *
     * @param payNo the value for tp_order.pay_no
     *
     * @mbggenerated
     */
    public void setPayNo(String payNo) {
        this.payNo = payNo == null ? null : payNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.pay_time
     *
     * @return the value of tp_order.pay_time
     *
     * @mbggenerated
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.pay_time
     *
     * @param payTime the value for tp_order.pay_time
     *
     * @mbggenerated
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.cancel_time
     *
     * @return the value of tp_order.cancel_time
     *
     * @mbggenerated
     */
    public Date getCancelTime() {
        return cancelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.cancel_time
     *
     * @param cancelTime the value for tp_order.cancel_time
     *
     * @mbggenerated
     */
    public void setCancelTime(Date cancelTime) {
        this.cancelTime = cancelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.refund_time
     *
     * @return the value of tp_order.refund_time
     *
     * @mbggenerated
     */
    public Date getRefundTime() {
        return refundTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.refund_time
     *
     * @param refundTime the value for tp_order.refund_time
     *
     * @mbggenerated
     */
    public void setRefundTime(Date refundTime) {
        this.refundTime = refundTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.is_receipt
     *
     * @return the value of tp_order.is_receipt
     *
     * @mbggenerated
     */
    public Integer getIsReceipt() {
        return isReceipt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.is_receipt
     *
     * @param isReceipt the value for tp_order.is_receipt
     *
     * @mbggenerated
     */
    public void setIsReceipt(Integer isReceipt) {
        this.isReceipt = isReceipt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.num
     *
     * @return the value of tp_order.num
     *
     * @mbggenerated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.num
     *
     * @param num the value for tp_order.num
     *
     * @mbggenerated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.act_id
     *
     * @return the value of tp_order.act_id
     *
     * @mbggenerated
     */
    public String getActId() {
        return actId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.act_id
     *
     * @param actId the value for tp_order.act_id
     *
     * @mbggenerated
     */
    public void setActId(String actId) {
        this.actId = actId == null ? null : actId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.ref_id
     *
     * @return the value of tp_order.ref_id
     *
     * @mbggenerated
     */
    public String getRefId() {
        return refId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.ref_id
     *
     * @param refId the value for tp_order.ref_id
     *
     * @mbggenerated
     */
    public void setRefId(String refId) {
        this.refId = refId == null ? null : refId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.is_bill
     *
     * @return the value of tp_order.is_bill
     *
     * @mbggenerated
     */
    public Integer getIsBill() {
        return isBill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.is_bill
     *
     * @param isBill the value for tp_order.is_bill
     *
     * @mbggenerated
     */
    public void setIsBill(Integer isBill) {
        this.isBill = isBill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_order
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orderNo=").append(orderNo);
        sb.append(", productName=").append(productName);
        sb.append(", uid=").append(uid);
        sb.append(", userName=").append(userName);
        sb.append(", mobile=").append(mobile);
        sb.append(", productId=").append(productId);
        sb.append(", orderDetailId=").append(orderDetailId);
        sb.append(", productType=").append(productType);
        sb.append(", productLevel=").append(productLevel);
        sb.append(", orderAmount=").append(orderAmount);
        sb.append(", discountAmount=").append(discountAmount);
        sb.append(", finalAmount=").append(finalAmount);
        sb.append(", refundAmount=").append(refundAmount);
        sb.append(", createTime=").append(createTime);
        sb.append(", status=").append(status);
        sb.append(", payType=").append(payType);
        sb.append(", payNo=").append(payNo);
        sb.append(", payTime=").append(payTime);
        sb.append(", cancelTime=").append(cancelTime);
        sb.append(", refundTime=").append(refundTime);
        sb.append(", isReceipt=").append(isReceipt);
        sb.append(", num=").append(num);
        sb.append(", actId=").append(actId);
        sb.append(", refId=").append(refId);
        sb.append(", isBill=").append(isBill);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}