package com.aotubuy.Model;

import java.io.Serializable;
import java.util.Date;

public class TPromotion implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_promotion.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_promotion.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_promotion.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_promotion.level
     *
     * @mbggenerated
     */
    private Long level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_promotion.enable
     *
     * @mbggenerated
     */
    private Boolean enable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_promotion.start_time
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_promotion.end_time
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_promotion.end_point
     *
     * @mbggenerated
     */
    private Boolean endPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_promotion.rule
     *
     * @mbggenerated
     */
    private String rule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_promotion.coupon_type
     *
     * @mbggenerated
     */
    private String couponType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_promotion.events
     *
     * @mbggenerated
     */
    private String events;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_promotion.page_url
     *
     * @mbggenerated
     */
    private String pageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_promotion
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_promotion.id
     *
     * @return the value of t_promotion.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_promotion.id
     *
     * @param id the value for t_promotion.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_promotion.name
     *
     * @return the value of t_promotion.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_promotion.name
     *
     * @param name the value for t_promotion.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_promotion.description
     *
     * @return the value of t_promotion.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_promotion.description
     *
     * @param description the value for t_promotion.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_promotion.level
     *
     * @return the value of t_promotion.level
     *
     * @mbggenerated
     */
    public Long getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_promotion.level
     *
     * @param level the value for t_promotion.level
     *
     * @mbggenerated
     */
    public void setLevel(Long level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_promotion.enable
     *
     * @return the value of t_promotion.enable
     *
     * @mbggenerated
     */
    public Boolean getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_promotion.enable
     *
     * @param enable the value for t_promotion.enable
     *
     * @mbggenerated
     */
    public void setEnable(Boolean enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_promotion.start_time
     *
     * @return the value of t_promotion.start_time
     *
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_promotion.start_time
     *
     * @param startTime the value for t_promotion.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_promotion.end_time
     *
     * @return the value of t_promotion.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_promotion.end_time
     *
     * @param endTime the value for t_promotion.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_promotion.end_point
     *
     * @return the value of t_promotion.end_point
     *
     * @mbggenerated
     */
    public Boolean getEndPoint() {
        return endPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_promotion.end_point
     *
     * @param endPoint the value for t_promotion.end_point
     *
     * @mbggenerated
     */
    public void setEndPoint(Boolean endPoint) {
        this.endPoint = endPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_promotion.rule
     *
     * @return the value of t_promotion.rule
     *
     * @mbggenerated
     */
    public String getRule() {
        return rule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_promotion.rule
     *
     * @param rule the value for t_promotion.rule
     *
     * @mbggenerated
     */
    public void setRule(String rule) {
        this.rule = rule == null ? null : rule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_promotion.coupon_type
     *
     * @return the value of t_promotion.coupon_type
     *
     * @mbggenerated
     */
    public String getCouponType() {
        return couponType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_promotion.coupon_type
     *
     * @param couponType the value for t_promotion.coupon_type
     *
     * @mbggenerated
     */
    public void setCouponType(String couponType) {
        this.couponType = couponType == null ? null : couponType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_promotion.events
     *
     * @return the value of t_promotion.events
     *
     * @mbggenerated
     */
    public String getEvents() {
        return events;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_promotion.events
     *
     * @param events the value for t_promotion.events
     *
     * @mbggenerated
     */
    public void setEvents(String events) {
        this.events = events == null ? null : events.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_promotion.page_url
     *
     * @return the value of t_promotion.page_url
     *
     * @mbggenerated
     */
    public String getPageUrl() {
        return pageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_promotion.page_url
     *
     * @param pageUrl the value for t_promotion.page_url
     *
     * @mbggenerated
     */
    public void setPageUrl(String pageUrl) {
        this.pageUrl = pageUrl == null ? null : pageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_promotion
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", description=").append(description);
        sb.append(", level=").append(level);
        sb.append(", enable=").append(enable);
        sb.append(", startTime=").append(startTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", endPoint=").append(endPoint);
        sb.append(", rule=").append(rule);
        sb.append(", couponType=").append(couponType);
        sb.append(", events=").append(events);
        sb.append(", pageUrl=").append(pageUrl);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}