package com.aotubuy.Model;

import java.io.Serializable;
import java.util.Date;

public class TStatisticBaidu implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_statistic_baidu.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_statistic_baidu.site_id
     *
     * @mbggenerated
     */
    private String siteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_statistic_baidu.date
     *
     * @mbggenerated
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_statistic_baidu.time
     *
     * @mbggenerated
     */
    private Integer time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_statistic_baidu.pv_count
     *
     * @mbggenerated
     */
    private Long pvCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_statistic_baidu.visitor_count
     *
     * @mbggenerated
     */
    private Long visitorCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_statistic_baidu.ip_count
     *
     * @mbggenerated
     */
    private Long ipCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_statistic_baidu.avg_visit_time
     *
     * @mbggenerated
     */
    private Long avgVisitTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_statistic_baidu.bounce_ratio
     *
     * @mbggenerated
     */
    private Long bounceRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_statistic_baidu.trans_count
     *
     * @mbggenerated
     */
    private Long transCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_statistic_baidu.contri_pv
     *
     * @mbggenerated
     */
    private Long contriPv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_statistic_baidu.gran
     *
     * @mbggenerated
     */
    private String gran;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_statistic_baidu
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_statistic_baidu.id
     *
     * @return the value of t_statistic_baidu.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_statistic_baidu.id
     *
     * @param id the value for t_statistic_baidu.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_statistic_baidu.site_id
     *
     * @return the value of t_statistic_baidu.site_id
     *
     * @mbggenerated
     */
    public String getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_statistic_baidu.site_id
     *
     * @param siteId the value for t_statistic_baidu.site_id
     *
     * @mbggenerated
     */
    public void setSiteId(String siteId) {
        this.siteId = siteId == null ? null : siteId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_statistic_baidu.date
     *
     * @return the value of t_statistic_baidu.date
     *
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_statistic_baidu.date
     *
     * @param date the value for t_statistic_baidu.date
     *
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_statistic_baidu.time
     *
     * @return the value of t_statistic_baidu.time
     *
     * @mbggenerated
     */
    public Integer getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_statistic_baidu.time
     *
     * @param time the value for t_statistic_baidu.time
     *
     * @mbggenerated
     */
    public void setTime(Integer time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_statistic_baidu.pv_count
     *
     * @return the value of t_statistic_baidu.pv_count
     *
     * @mbggenerated
     */
    public Long getPvCount() {
        return pvCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_statistic_baidu.pv_count
     *
     * @param pvCount the value for t_statistic_baidu.pv_count
     *
     * @mbggenerated
     */
    public void setPvCount(Long pvCount) {
        this.pvCount = pvCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_statistic_baidu.visitor_count
     *
     * @return the value of t_statistic_baidu.visitor_count
     *
     * @mbggenerated
     */
    public Long getVisitorCount() {
        return visitorCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_statistic_baidu.visitor_count
     *
     * @param visitorCount the value for t_statistic_baidu.visitor_count
     *
     * @mbggenerated
     */
    public void setVisitorCount(Long visitorCount) {
        this.visitorCount = visitorCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_statistic_baidu.ip_count
     *
     * @return the value of t_statistic_baidu.ip_count
     *
     * @mbggenerated
     */
    public Long getIpCount() {
        return ipCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_statistic_baidu.ip_count
     *
     * @param ipCount the value for t_statistic_baidu.ip_count
     *
     * @mbggenerated
     */
    public void setIpCount(Long ipCount) {
        this.ipCount = ipCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_statistic_baidu.avg_visit_time
     *
     * @return the value of t_statistic_baidu.avg_visit_time
     *
     * @mbggenerated
     */
    public Long getAvgVisitTime() {
        return avgVisitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_statistic_baidu.avg_visit_time
     *
     * @param avgVisitTime the value for t_statistic_baidu.avg_visit_time
     *
     * @mbggenerated
     */
    public void setAvgVisitTime(Long avgVisitTime) {
        this.avgVisitTime = avgVisitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_statistic_baidu.bounce_ratio
     *
     * @return the value of t_statistic_baidu.bounce_ratio
     *
     * @mbggenerated
     */
    public Long getBounceRatio() {
        return bounceRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_statistic_baidu.bounce_ratio
     *
     * @param bounceRatio the value for t_statistic_baidu.bounce_ratio
     *
     * @mbggenerated
     */
    public void setBounceRatio(Long bounceRatio) {
        this.bounceRatio = bounceRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_statistic_baidu.trans_count
     *
     * @return the value of t_statistic_baidu.trans_count
     *
     * @mbggenerated
     */
    public Long getTransCount() {
        return transCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_statistic_baidu.trans_count
     *
     * @param transCount the value for t_statistic_baidu.trans_count
     *
     * @mbggenerated
     */
    public void setTransCount(Long transCount) {
        this.transCount = transCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_statistic_baidu.contri_pv
     *
     * @return the value of t_statistic_baidu.contri_pv
     *
     * @mbggenerated
     */
    public Long getContriPv() {
        return contriPv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_statistic_baidu.contri_pv
     *
     * @param contriPv the value for t_statistic_baidu.contri_pv
     *
     * @mbggenerated
     */
    public void setContriPv(Long contriPv) {
        this.contriPv = contriPv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_statistic_baidu.gran
     *
     * @return the value of t_statistic_baidu.gran
     *
     * @mbggenerated
     */
    public String getGran() {
        return gran;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_statistic_baidu.gran
     *
     * @param gran the value for t_statistic_baidu.gran
     *
     * @mbggenerated
     */
    public void setGran(String gran) {
        this.gran = gran == null ? null : gran.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_statistic_baidu
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", siteId=").append(siteId);
        sb.append(", date=").append(date);
        sb.append(", time=").append(time);
        sb.append(", pvCount=").append(pvCount);
        sb.append(", visitorCount=").append(visitorCount);
        sb.append(", ipCount=").append(ipCount);
        sb.append(", avgVisitTime=").append(avgVisitTime);
        sb.append(", bounceRatio=").append(bounceRatio);
        sb.append(", transCount=").append(transCount);
        sb.append(", contriPv=").append(contriPv);
        sb.append(", gran=").append(gran);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}