package com.aotubuy.Dao;

import com.aotubuy.Model.DollNavigation;
import java.util.List;

public interface DollNavigationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doll_navigation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doll_navigation
     *
     * @mbggenerated
     */
    int insert(DollNavigation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doll_navigation
     *
     * @mbggenerated
     */
    DollNavigation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doll_navigation
     *
     * @mbggenerated
     */
    List<DollNavigation> selectAll();


    /**select in use*/
    List<DollNavigation> selectAllInUse();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doll_navigation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DollNavigation record);
}