package com.aotubuy.Dao;

import com.aotubuy.Model.DollAd;
import java.util.List;

public interface DollAdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doll_ad
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer adId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doll_ad
     *
     * @mbggenerated
     */
    int insert(DollAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doll_ad
     *
     * @mbggenerated
     */
    DollAd selectByPrimaryKey(Integer adId);
    DollAd selectIndexTopBannerAd();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doll_ad
     *
     * @mbggenerated
     */
    List<DollAd> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doll_ad
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DollAd record);
}