package com.aotubuy.Dao;

import com.aotubuy.Model.DollSmsLog;
import java.util.List;

public interface DollSmsLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doll_sms_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doll_sms_log
     *
     * @mbggenerated
     */
    int insert(DollSmsLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doll_sms_log
     *
     * @mbggenerated
     */
    DollSmsLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doll_sms_log
     *
     * @mbggenerated
     */
    List<DollSmsLog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doll_sms_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DollSmsLog record);

List<DollSmsLog> selectByMobileAndSession(String mobile,String sessionId);

}