package com.aotubuy.Dao;

import com.aotubuy.Model.DollUsers;
import java.util.List;

public interface DollUsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doll_users
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doll_users
     *
     * @mbggenerated
     */
    int insert(DollUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doll_users
     *
     * @mbggenerated
     */
    DollUsers selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doll_users
     *
     * @mbggenerated
     */
    List<DollUsers> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doll_users
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DollUsers record);

    /**get userDetail by email or mobileNumber*/
    DollUsers selectByUserNameOrEmail(String userName);
}