package com.aotubuy.Dao;

import com.aotubuy.Model.DollConfig;
import java.util.List;

public interface DollConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doll_config
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doll_config
     *
     * @mbggenerated
     */
    int insert(DollConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doll_config
     *
     * @mbggenerated
     */
    DollConfig selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doll_config
     *
     * @mbggenerated
     */
    List<DollConfig> selectAll();
List<DollConfig> getShopInfos();
    DollConfig getShopHotKeyWords();
    List<DollConfig> getSmsConfigs();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doll_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DollConfig record);
}