package com.aotubuy.Dao;

import com.aotubuy.Model.TActivity;
import java.util.List;

public interface TActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity
     *
     * @mbggenerated
     */
    int insert(TActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity
     *
     * @mbggenerated
     */
    TActivity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity
     *
     * @mbggenerated
     */
    List<TActivity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TActivity record);
}