package com.aotubuy.Dao;

import com.aotubuy.Model.TActivityEntryForm;
import java.util.List;

public interface TActivityEntryFormMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_entry_form
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_entry_form
     *
     * @mbggenerated
     */
    int insert(TActivityEntryForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_entry_form
     *
     * @mbggenerated
     */
    TActivityEntryForm selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_entry_form
     *
     * @mbggenerated
     */
    List<TActivityEntryForm> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_entry_form
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TActivityEntryForm record);
}