package com.aotubuy.Dao;

import com.aotubuy.Model.TActivityAttr;
import java.util.List;

public interface TActivityAttrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_attr
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_attr
     *
     * @mbggenerated
     */
    int insert(TActivityAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_attr
     *
     * @mbggenerated
     */
    TActivityAttr selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_attr
     *
     * @mbggenerated
     */
    List<TActivityAttr> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_attr
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TActivityAttr record);
}