package com.aotubuy.Dao;

import com.aotubuy.Model.TActivityPeriod;
import java.util.List;

public interface TActivityPeriodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_period
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_period
     *
     * @mbggenerated
     */
    int insert(TActivityPeriod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_period
     *
     * @mbggenerated
     */
    TActivityPeriod selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_period
     *
     * @mbggenerated
     */
    List<TActivityPeriod> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_period
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TActivityPeriod record);
}