package com.aotubuy.Dao;

import com.aotubuy.Model.TBespeak;
import java.util.List;

public interface TBespeakMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bespeak
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bespeak
     *
     * @mbggenerated
     */
    int insert(TBespeak record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bespeak
     *
     * @mbggenerated
     */
    TBespeak selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bespeak
     *
     * @mbggenerated
     */
    List<TBespeak> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bespeak
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TBespeak record);
}