package com.aotubuy.Dao;

import com.aotubuy.Model.TCouponSendRule;
import java.util.List;

public interface TCouponSendRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon_send_rule
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon_send_rule
     *
     * @mbggenerated
     */
    int insert(TCouponSendRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon_send_rule
     *
     * @mbggenerated
     */
    TCouponSendRule selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon_send_rule
     *
     * @mbggenerated
     */
    List<TCouponSendRule> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon_send_rule
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TCouponSendRule record);
}