package com.aotubuy.Dao;

import com.aotubuy.Model.TCoupon;
import java.util.List;

public interface TCouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon
     *
     * @mbggenerated
     */
    int insert(TCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon
     *
     * @mbggenerated
     */
    TCoupon selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon
     *
     * @mbggenerated
     */
    List<TCoupon> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TCoupon record);
}