package com.aotubuy.Dao;

import com.aotubuy.Model.TLottery;
import java.util.List;

public interface TLotteryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lottery
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lottery
     *
     * @mbggenerated
     */
    int insert(TLottery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lottery
     *
     * @mbggenerated
     */
    TLottery selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lottery
     *
     * @mbggenerated
     */
    List<TLottery> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lottery
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TLottery record);
}