package com.aotubuy.Dao;

import com.aotubuy.Model.TpOrder;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TpOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("orderNo") String orderNo, @Param("productName") String productName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_order
     *
     * @mbggenerated
     */
    int insert(TpOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_order
     *
     * @mbggenerated
     */
    TpOrder selectByPrimaryKey(@Param("orderNo") String orderNo, @Param("productName") String productName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_order
     *
     * @mbggenerated
     */
    List<TpOrder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TpOrder record);
}