package com.aotubuy.Dao;

import com.aotubuy.Model.TPromotion;
import java.util.List;

public interface TPromotionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_promotion
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_promotion
     *
     * @mbggenerated
     */
    int insert(TPromotion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_promotion
     *
     * @mbggenerated
     */
    TPromotion selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_promotion
     *
     * @mbggenerated
     */
    List<TPromotion> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_promotion
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TPromotion record);
}