package com.aotubuy.Dao;

import com.aotubuy.Model.TStaff;
import java.util.List;

public interface TStaffMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_staff
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_staff
     *
     * @mbggenerated
     */
    int insert(TStaff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_staff
     *
     * @mbggenerated
     */
    TStaff selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_staff
     *
     * @mbggenerated
     */
    List<TStaff> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_staff
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TStaff record);
}